# Generated by Django 5.1.3 on 2024-11-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novena', '0002_alter_patient_state_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='patient',
        ),
        migrations.AddField(
            model_name='message',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_message', to='novena.patient'),
        ),
    ]
