# Generated by Django 5.1.3 on 2024-11-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novena', '0004_alter_message_host'),
        ('novena_dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='host',
        ),
        migrations.AddField(
            model_name='message',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_message', to='novena_dash.doctor'),
        ),
        migrations.AddField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_message', to='novena.patient'),
        ),
    ]
